### PR TITLE
Initial (basic) info about new landing page and Slack team

### PR DESCRIPTION
**Pull request by MiroHibler**
This is just the beginning ;)

### CODE REVIEW

**Comment by aadamsx** [comment]
Is there going to be a website with some sort of mission statement and maybe showing how to properly use Blaze (best practices/examples) at some point?  It looks like blazejs.com is registered -- who owns this anyhow?

**Comment by MiroHibler** [comment]
@aadamsx Yes, that's the general idea. The site is http://blazejs.com. There's not much yet but everyone is welcome to contribute :)

**Comment by mitar** [comment]
> Oops, no SSL for meteorjs.com just yet ;)

Hm, be a bit more precise with commit messages. You do not have to hurry so much. ;-) It is `blazejs`, not `meteorjs`. :-)

**Comment by MiroHibler** [comment]
Thanks for merge!

Btw, it wasn't a hurry but juggling between projects... ;)

**Pull request merged**
