### PR TITLE
Initial site

### PR DESCRIPTION
**Pull request by alexandesigner**
I worked in version of documentation for the blaze [Repository](https://github.com/alexandesigner/blazejs) and used the base of the documentation and in the Guide.. Using also the hexo. [Preview](http://alexandesigner.github.io/blazejs/docs)

After suggestion the @mitar https://github.com/meteor/blaze/issues/31#issuecomment-243540336 ... I gave an "improved" and I think it's a good start.. did deploy in that repository

### CODE REVIEW

**Comment by mitar** [comment]
Oho. This looks really great. This is static content or it is generated with a program?

**Comment by mitar** [comment]
I also like your README in that repository very much!

**Comment by alexandesigner** [comment]
Hey @mitar  this PR is static.. However he was generated using Hexo from my repository ``/docs``

He is just simple.. Use ``hexo generate`` he generates the static files in ``/public`` (which is what I sent in this PR); Perhaps I should add the main folder?? However, I figured it should run out of this branch, maybe on master in path ``/site``

**Comment by alexandesigner** [comment]
> I also like your README in that repository very much!

I think we could use it and add the information that is in the current Readme.. _(How to get involved.. slack.. )_

**Comment by mitar** [comment]
Yes, you should add source to `master` branch, `site` directory sounds good. And then we can use CircleCI to automatically generate content and push it to `gh-pages`.

**Comment by alexandesigner** [comment]
Did another PR https://github.com/meteor/blaze/pull/65 with the files and i changed the url pointing to the ``gh-pages`` aka http://meteor.github.io/blaze, all right ?

**Comment by mitar** [comment]
No, we use `http://blazejs.org/`. You do not have to expose `http://meteor.github.io/blaze` anywhere.

**Comment by mitar** [comment]
OK, let's close this pull request in favor of that one.

**Pull request closed without merging**
