### PR TITLE
WiP: Tutorial section in documentation

### PR DESCRIPTION
**Pull request by alexandesigner**
https://github.com/meteor/blaze/issues/270

I think it would be a good idea to add a section in the documentation "Tutorials" at first we can just migrate the Todo App but we would leave it free to add other tutorials to help the developers .. I am willing to start this task but would like to know what you guys think @mitar @dandv 

#### Do not do the merge yet, I'm starting the work .. If it's a good idea I'll finish the tutorial

### CODE REVIEW

**Comment by mitar** [comment]
Hm, this looks good. :-) Is code here related to github todo repo? It would be great if those two would be in sync, no? Or is this one even simpler?

**Comment by hwillson** [comment]
Hi guys - this looks like the start of the Blaze tutorial code located in http://github.com/meteor/tutorials. Just a heads up, the format / structure of that tutorial is likely going to change soon. For more info, see https://github.com/meteor/tutorials/pull/167. That PR will eventually encompass the Blaze todo tutorial as well. I don't think you'll want to replicate that tutorial in the Blaze repo, since it's already going to be hosted alongside the React tutorial (and hopefully eventually a Vue tutorial), all managed under one repo, and deployed to Netlify.

**Comment by alexandesigner** [comment]
@mitar the @hwillson It ended up answering your question for me, but somehow I'm glad that this [conversion](https://github.com/meteor/tutorials/pull/167) is being done. The ideal is to synchronize the works. I will leave in stand-by this PR and focus the work in the repository tutorials in meteor next re-use the work done there. @hwilson let me know if I can help somewhere.

**Comment by filipenevola** [comment]
Hi, as the CLA is not signed we can't proceed with this PR. If you want to proceed please comment here.

**Pull request closed without merging**
