### PR TITLE
Release 2.6.2

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by zodern** [comment]
I'm not sure if you are planning to publish from this branch or master, so I wanted to make sure you knew that #410 was already merged into master, so it is missing in this branch.

**Comment by jankapunkt** [comment]
@zodern @StorytellerCZ I updated the PR so it should now be included. From my view this is ready to publish.

**Comment by StorytellerCZ** [comment]
@Grubba27 I'll prepare a changelog and then we can go ahead with a release.

**Comment by Grubba27** [comment]
Ping me on Slack, I find it easier to me set alarms when it is ready to go. I will make the release from this branch probably.

**Comment by StorytellerCZ** [comment]
@Grubba27 done!

**Review by jankapunkt — APPROVED** [review]

**Pull request merged**
