### PR TITLE
Converting Template to a class

### PR DESCRIPTION
**Pull request by mitar**
TODO:
- [ ] update documentation and terminology everywhere

See: #98

### CODE REVIEW

**Comment by mitar** [comment]
Please test. :-) It should be backwards compatible if you have not done any strange things. But it would be people using Blaze extensively would test it.

**Comment by mitar** [comment]
Not all tests are passing yet. Maybe wait a bit before testing it with extra code. :-)

**Comment by aadamsx** [comment]
How would we test something like this on an existing project running 1.3.5.1?

**Comment by mitar** [comment]
I [documented how to run Meteor with these packages here](https://github.com/meteor/blaze/blob/master/CONTRIBUTING.md). I think it should just work with 1.3.5.1 as well, but see.

If you have `Package.blaze.Blaze.Template.newRenderFunction` in the console, then you are running this branch.

**Comment by arist0tl3** [comment]
So I just walked through a shorter one of our regression tests with the `template-class` branch and everything looked good, functionally.

I did notice a ton of warning logs that looked like:

`Assigning helper with Template.X.Y = ... is deprecated.  Use Template.X.helpers(...) instead.`

But, in each instance, Y wasn't actually a helper, but a nested template. So, for the following:

```
<template name="myForm">
  {{> myInput args...}}
</template>

<template name="myInput">
  <!-- stuff -->
</template>
```

I am seeing:

`Assigning helper with Template.myForm.myInput = ... is deprecated.  Use Template.myForm.helpers(...) instead.`

@mitar If you want more info, let me know as it's a private repo.

**Comment by filipenevola** [comment]
Hi @mitar, do you want to have this PR merged yet?

If yes, please fix the conflict and comment here so we can re-open, review and merge.

**Pull request closed without merging**
