### PR TITLE
New page, and change config.yml navbar-donate

### PR DESCRIPTION
**Pull request by janat08**
Doesn't look like config.yml changes made it:

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: BlazeJS
subtitle: Developers
description:
author:
language:
timezone:
apis:
  # marketo: 627-RVJ-941
  # segment: zQx6cQifkTU79E3L0XAnmrOXP2A5bC6r
  # docsearch:
  #   apiKey: bdf6b09d12024f6bae3631a0dfdd4a7f
  #   indexName: meteor_api_guide
versions:
  - '2.1.8'

# This setting also defines the page order used to generate the Previous/Next links at the bottom of each page
sidebar_categories:
  null:
    - index
    - framework-packages
    - changelog
  GUIDE:
    - guide/introduction
    - guide/spacebars
    - guide/reusable-components
    - guide/smart-components
    - guide/reusing-code
    - guide/understanding-blaze
    - guide/routing
  API:
    - api/templates
    - api/blaze
    - api/spacebars

github_repo: 'meteor/blaze'
content_root: 'site/source'

# themeing
favicon: '/logo/icon.ico'

logo:
  nav_mobile: '/logo/logo.png'
  url: 'http://blazejs.org'
  title: 'BlazeJS'
  subtitle: 'Developers'

nav_links:
  'Guide':
    url: http://blazejs.org/guide/introduction.html
  'API Docs':
    url: http://blazejs.org/api/templates.html
  'Forums':
    url: https://forums.meteor.com/c/blaze
    target: _new
  'Donate':
    url: https://opencollective.com/blaze
    target: _new

social_links:
  github: 'https://github.com/meteor/blaze'
  twitter: '@meteor'


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blazejs.org/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - circle.yml

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: meteor
api_box:
  data_file: 'data/data.js'
marked:
  breaks: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:
```

### CODE REVIEW

**Comment by janat08** [comment]
#258 donations

**Comment by janat08** [comment]
I feel like recommending babrahams:constellation for debugging would also be helpful, since other frameworks have debuggers of their own.

**Comment by janat08** [comment]
This tries to recommend some of the packages patterned after other frameworks such as vue and react, and tools such as reval and debugger. You could perhaps go as far as to promote the new vue tracker in there since people question where blaze.js is going profusely on forums.
@mitar

**Comment by mitar** [comment]
So as it looks, this is just one file change? How does this integrate with the rest of documentation?

So to me this feels like unfinished PR.

**Comment by janat08** [comment]
I was hoping that navbar changed and extra page could be added which I think demand admin to do it in both cases or something. I'm also certain that it's rather poorly written.

**Comment by filipenevola** [comment]
Hi, as the CLA is not signed we can't proceed with this PR. If you want to proceed please comment here.

**Pull request closed without merging**
