### PR TITLE
Added API box from meteor docs

### PR DESCRIPTION
**Pull request by tmeasday**
Moved API docs over from:
 - http://docs.meteor.com/api/templates.html
 - http://docs.meteor.com/api/blaze.html

It's kind of ugly to copy this much stuff over, I'd like to make an
jsdoc_api_box hexo plugin, but there's so much specific stuff in here
that needs to be factored out properly (mainly the jsdoc/ scripts and
config).

Maybe some can do it some day but for now we'll have some duplication.
Hopefully we won't need to change it much.

### CODE REVIEW

**Comment by mitar** [comment]
Thanks! Is it from your side ready? I would just merge it and we can iterate on content later.

**Comment by tmeasday** [comment]
Yeah, once this is merged, I'll setup pointers from docs.meteor.com

**Comment by tmeasday** [comment]
Although I think maybe some styling is needed before merging it, btw.

**Comment by mitar** [comment]
OK, let's merge and break things and improve later. :-)

I am not good with styling, so I will leave to @alexandesigner to see if he thinks there are things to improve.

**Comment by mitar** [comment]
Hm, I am getting errors:

```
Error: ENOENT: no such file or directory, open 'data/data.js'
```

**Comment by tmeasday** [comment]
@mitar are you `npm start`-ing?

**Comment by mitar** [comment]
Inside `site` directory:

```
npm install
npm start
```

Like it is written in README there.

**Comment by tmeasday** [comment]
Sorry, try now.

**Comment by mitar** [comment]
Deployed. Yes, some reorganization and cleanup will be needed. But it is getting better and better.

**Comment by mitar** [comment]
Code links are pointing to Meteor repository.

**Comment by tmeasday** [comment]
Fixed, thanks.

**Comment by tmeasday** [comment]
Updated docs.meteor.com with links:
 - http://docs.meteor.com/api/templates.html
 - http://docs.meteor.com/api/blaze.html

**Pull request merged**
