### PR TITLE
Architecture overview for all Blaze packages added.

### PR DESCRIPTION
**Pull request by jankapunkt**
This PR will provide a detailed architecture overview for Blaze and the related packages.
In order to have an easier entry for newcomers it is essential to provide a starting point for understanding Blaze.

The following overviews have been provided:

## All Blaze packages and their dependencies

all packages

## Package `templating-tools`

package templating-tools

## Package `static-html`

package static-html

### CODE REVIEW

**Comment by filipenevola** [comment]
Hi @jankapunkt, what is left here?

I believe it's good to be merged, what do you think?

**Comment by jankapunkt** [comment]
It's incomplete, since there are a few packages left but you can merge and there may be further overviews in future contributions.

**Comment by filipenevola** [comment]
@jankapunkt could you remove the draft status then?

**Comment by filipenevola** [comment]
Hi, tests are fixed on `master`. Please update your branch.

**Comment by filipenevola** [comment]
@jankapunkt I already updated your branch.

Do you want to publish the existent diagrams in the site or as a readme?

I think only this is missing now.

**Comment by jankapunkt** [comment]
Hey @filipenevola I think this can be in the Readme for now. Once new features are worked into Blaze we may update the Website anyway and until then I may have added more diagrams. Sorry for not removing the draft status I am only on mobile for a few days and the mobile app does not have the function to change this kind of status.

**Comment by filipenevola** [comment]
@jankapunkt no problem.

Your PR is merged and the file OVERVIEW.md is created and linked in the main README.

**Comment by jankapunkt** [comment]
@filipenevola thank you for that

**Pull request merged**
