### PR TITLE
modernize htmljs, html-tools, blaze-tools, spacebars-compiler, etc

### PR DESCRIPTION
**Pull request by nathan-muir**
Hi,

Some old changes that I didn't create a PR for, as there was no maintainer.

Just went through and converted a few packages to imports/exports, but kept the existing inter-package api's the same.

### CODE REVIEW

**Comment by filipenevola** [comment]
Hi @nathan-muir thank you.

As you can see [here](https://app.circleci.com/pipelines/github/meteor/blaze/39/workflows/11ab9817-d0ee-4c6a-ae38-6f683e0e5c13/jobs/395) there are 10 tests failing:

`passed/expected/failed/total 285 / 0 / 10 / 295`

On master they are all passing, it's probably something that you changed in your branch.

Could you take a look?

**Comment by nathan-muir** [comment]
@filipenevola Tests should be passing now, but ci/circleci is stuck?

**Comment by filipenevola** [comment]
@nathan-muir the tests are passing, the job stuck on CircleCI are the old ones as this branch was old I believe.

**Comment by filipenevola** [comment]
I think we could create a branch with your changes + hot-module-replacement and have a new beta.

What do you think @nathan-muir @zodern ?

Maybe we are even going to get a conflict between these two branches.

**Comment by filipenevola** [comment]
@nathan-muir could you check the conflicts?

As you refactored the code I believe you are the best person to understand what is the version that should be maintained.

The conflicts are probably coming from the HMR changes.

**Comment by nathan-muir** [comment]
@filipenevola Should be solved now

**Comment by filipenevola** [comment]
Great.

**Pull request merged**
