### PR TITLE
Release 2.8

### PR DESCRIPTION
**Pull request by Grubba27**
Making Blaze truly async!!! And deprecating UI

### CODE REVIEW

**Review by jankapunkt — APPROVED** [review]

**Comment by jankapunkt** [comment]
Looks all good. Do you intend to publish an RC or directly the final 2.8.0

**Comment by StorytellerCZ** [comment]
I see that the Hexo update was merged in as well.

**Comment by Grubba27** [comment]
I want to publish it directly! If you all agree

**Comment by Grubba27** [comment]
I have updated the history.md as well

**Comment by StorytellerCZ** [comment]
Can we merge the rest from the 2.8 milestone?

**Comment by Grubba27** [comment]
Sure! If those prs are okay

**Comment by Grubba27** [comment]
I Will leave https://github.com/meteor/blaze/pull/436 (https://github.com/meteor/blaze/pull/453) out for now because is not sure if @jankapunkt approved it and it could come as a 2.8.1 patch I think

**Comment by Grubba27** [comment]
Screenshot 2023-12-29 at 11 06 01

We have a 2.8 version!!

**Pull request merged**
