### PR TITLE
Add {{elseif}} sugar syntax

### PR DESCRIPTION
**Pull request by nathantreid**
Implements #39.

``` handlebars
{{#if counterIsAt 2}}
    test
{{elseif counterIsAt 3}}
    test3
{{elseif counterIsAt 4}}
    test4
{{else}}
    test5
{{/if}}
```

Working example here: https://github.com/nathantreid/blaze-test-issue-39

### CODE REVIEW

**Comment by mitar** [comment]
Wohoooo, so great!

**Comment by kulttuuri** [comment]
This would be awesome to have. Great work! 👍

**Comment by grsabreu** [comment]
Any updates on this?

**Comment by mitar** [comment]
Waiting for #20 and that we release first community Blaze version. I would like that one to be without extra features, just bugfixes. And then we can start adding features.

**Comment by necmettin** [comment]
Forgive me if this was discussed (and decided) before, or if we shouldn't discuss PRs; but would it not be nicer, more in-line with Blaze syntax (and easier to read) if we used `{{#elseif` (maybe even `{{#else` at some point?) instead of `{{elseif` ?

**Comment by mitar** [comment]
We should discuss PRs!!! And this is the perfect place.

You are bringing up a great point. But Blaze uses `{{else}}`. So it is a good question which one it should be. I personally vote for `{{elseif}}`.

**Comment by nathantreid** [comment]
For Blaze 1.x, I think it should match the current Blaze if / else structure, so `{{elseif}}` is my vote. 
That said, I actually prefer {{#elseif}} and {{#else}} (I don't think it makes sense to have `{{#elseif}}` with `{{else}}`).
I think it's easier to visually parse the blocks with the `#`.
``` handlebars
{{#if abc}}
  ...
{{#elseif def}}
  ...
{{#else}}
  ...
{{/if}}
```
vs
``` handlebars
{{#if abc}}
  ...
{{elseif def}}
  ...
{{else}}
  ...
{{/if}}
```

**Comment by mitar** [comment]
OK, maybe open an issue with proposal to change `{{else}}` and `{{elseif`}}` to `{{#else}}` and `{{#elseif}}` and I will put it into 2.0 milestone and open it for discussion. Let's see through time how people will upvote or downvote it and see then for 2.0.

**Comment by exKAZUu** [comment]
I think v1 should keep compatibility as much as possible. So I'd like to vote for `{{elseif}}`.

**Comment by stubailo** [comment]
Note that a lot of this syntax is based on handlebars. So it might be interesting to decide whether or not the future of Blaze/Spacebars should include a desire to remain close to that syntax. My hunch would be "no" since probably nobody cares about handlebars these days, and sticking to handlebars was a really big limitation in Blaze for a while.

**Comment by mitar** [comment]
@nathantreid: This is great work. Can you please resolve merge conflicts? And add also all changes to documentation (spacebars API, mention this also somewhere in guide, blaze itself, and so on)?

**Comment by mitar** [comment]
BTW, Handlebars seems to have [else if](https://stackoverflow.com/questions/10736907/handlebars-js-else-if).

See also [example in documentation](http://handlebarsjs.com/block_helpers.html). It seems the syntax is:

```handlebars
{{else if isInactive}}
```

And also:

```handlebars
{{else unless isInactive}}
```

Or in general it seems it can be `{{else <any block helper>}}`.

> It is not necessary to use the same helper in subsequent calls, the unless helper could be used in the else portion as with any other helper. When the helper values are different, the closing mustache should match the opening helper name. 

While I dislike this syntax, I see benefit of having it match Handlebars, and benefit of supporting any block helper. Implementation might be a bit trickier to implement, but this sugar is easy to do:

```handlebars
{{#if foo}}

{{else something bar}}

{{/if}}
```

Becomes:

``
```handlebars
{{#if foo}}

{{else}}
  {{#something bar}}

  {{/something}}
{{/if}}
```

@nathantreid, could you implement it this way?

**Comment by stubailo** [comment]
Yikes.... that seems kind of odd. Are we sure we want to think about handlebars at all? Honestly Handlebars doesn't seem that well designed to start with.

**Comment by mitar** [comment]
For this particular feature I think I would. I would change what `this` means inside a template, but for syntax I would try to stick with Handlebars.

**Comment by mitar** [comment]
Also, this syntax seems to map nicely to the sugar we are trying to make.

**Comment by nathantreid** [comment]
I also think that the {{else if}} syntax looks odd, perhaps we could put that up for a vote?
I personally don't have any desire to match Handlebars going forward, unless of course it's because the syntax is actually makes a lot of sense on its own.

**Comment by mitar** [comment]
It is not just a syntax here, but also a feature. So that you can use any block helper in this way. `elseif` does not support that. I think that a feature of `else <blockname>` is a good one. I use quite some custom block helpers (Blaze Components add extra power to them).

**Comment by mitar** [comment]
@nathantreid, I really love your work here and I think many people would like to see this in. But I also really like that the Handlebars syntax work with arbitrary block helpers. I think that block helpers are really powerful feature of Blaze and with allowing such chaining of them it would be really powerful. Currently block helpers were a bit strange to use because what if you had only two cases, but now you can potentially get multiple cases supported, not just true/false.

Could you please update the pull request to support arbitrary block helpers?

**Comment by mitar** [comment]
So something like this could then work:

```handlebars
{{#tab title="Foo"}}

{{else tab title="Bar"}}

{{else tab title="Baz"}}

{{/tab}}
```

And have a block helper which renders dynamically tabs, opens/closes them, etc.

**Comment by nathantreid** [comment]
I'd be happy too, but I'm swamped right now IRL. If someone else wants to have a go at it, be my guest. Otherwise, I'll try to get to it as soon as I can.

**Comment by mitar** [comment]
No worries. I just wanted to make sure we have a path forward.

**Comment by mitar** [comment]
Any progress here? Anyone else wants to tackle this?

**Comment by kulttuuri** [comment]
This would be fantastic feature to have. @nathantreid still busy with things IRL? :)

**Comment by mitar** [comment]
I cleaned `master` branch to remove all Meteor history (#112). This means the pull request should be also updated to new history to not base it on old commits. Sorry for this extra work.

**Comment by mitar** [comment]
With 2fa3cabcf446a1db571fd63aabea60b974d2c1a0 I implemented the Handlebars syntax for chaining block tags. I am closing this pull request in favor of that.

**Comment by mitar** [comment]
Released as 2.3.0. You have to update templating package.

**Pull request closed without merging**
