### PR TITLE
Fix HTML.isArray to work across frames.

### PR DESCRIPTION
**Pull request by brucejo75**
Title says it all.

See issue #275.

Also, for reference I ran into a similar issue earlier in meteor that was resolved with pr https://github.com/meteor/meteor/pull/8401.  I learned the hard way to retain both forms of Array detection 😄 .

### CODE REVIEW

**Comment by brucejo75** [comment]
Looks like a build issue?

**Comment by filipenevola** [comment]
Hi @brucejo75, do you want to have this PR merged yet?

If yes, please comment here so we can re-open, review and merge.

**Comment by brucejo75** [comment]
Sorry, yes I would like this merged... I will take another look if you can reopen.

**Comment by filipenevola** [comment]
@brucejo75 done.

**Comment by brucejo75** [comment]
@filipenevola, I think these are generic build errors?  They have nothing to do with my fix...  Is someone working on the Blaze regression tests?

> Service alert: Your project references CircleCI 1.0 or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue. Learn More

> An error occurred in .circleci/config.yml

**Comment by filipenevola** [comment]
Yes, here https://github.com/meteor/blaze/pull/317

Blaze tests were using CircleCI 1.0 but it was deprecated.

**Comment by filipenevola** [comment]
Hi, tests are fixed on `master`. Please update your branch.

**Comment by brucejo75** [comment]
@filipenevola, looks like Blaze Tests succeeded but the 1st 2 checks (CLA, ci/circleci) are stuck?

**Comment by filipenevola** [comment]
@brucejo75 they were the old tests.

**Pull request merged**
