### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by jankapunkt**
I plan to do some further contributions and found the local tests to be hard to setup. I wrapped them into the test-app project and updated the contribution documentation to make local testing easier.

### CODE REVIEW

**Comment by filipenevola** [comment]
Hi @jankapunkt I would like to move this PR forward, what is missing here?

**Comment by jankapunkt** [comment]
From end it's good so far, the Checks are failing because of the CI is not updated. You should however be good to run the tests locally by following the contributions.md section on testing. I would try on a GitHub actions CI in a separate PR

**Comment by brucejo75** [comment]
@filipenevola, are you going to accept and merge @jankapunkt changes?  Looks like the checks will never succeed because they need these fixes to run?

**Comment by filipenevola** [comment]
> @filipenevola, are you going to accept and merge @jankapunkt changes? Looks like the checks will never succeed because they need these fixes to run?

I'm working on this branch right now to try to have some testing running on CI. In any case I already ran it locally and the tests are all passing.

**Pull request merged**
