### PR TITLE
Async: update test app

### PR DESCRIPTION
**Pull request by jankapunkt**
This PR updates the `test-app` to Meteor 2.12 and each tracker dependency to 1.3.0. The previous `test-app` was set at Meteor 2.7.1 with Tracker at 1.2.0, causing a version conflict for Tracker.

### CODE REVIEW

**Comment by jankapunkt** [comment]
Note, when reviewing, the local tests currently failed at my machine with the following output:

```sh
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:80:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:80:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:81:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:81:8
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:82:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:82:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:83:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:83:8
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:84:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:84:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:85:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:85:8
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:86:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:86:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:87:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:87:8
(node:3918) UnhandledPromiseRejectionWarning: TypeError: Spacebars.call(...).catch is not a function
    at packages/local-test_spacebars.js:88:84
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:94:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:94:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:95:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:95:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:96:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:96:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:97:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:97:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:98:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:98:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:99:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.ok (packages/tinytest/tinytest.js:26:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:150:12)
    at packages/local-test_spacebars.js:99:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:100:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:100:8
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
Trying to report a test not in a fiber! You probably forgot to wrap a callback in bindEnvironment.
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:101:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:101:8
[object Object]
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:424:21)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:102:8
[object Object]
    at TestRun.onReport (packages/tinytest/tinytest_server.js:64:17)
    at TestRun._report (packages/tinytest/tinytest.js:659:10)
    at test.run.totalTime (packages/tinytest/tinytest.js:539:12)
    at TestCaseResults.onEvent (packages/tinytest/tinytest.js:426:18)
    at TestCaseResults.fail (packages/tinytest/tinytest.js:80:10)
    at TestCaseResults.equal (packages/tinytest/tinytest.js:147:12)
    at packages/local-test_spacebars.js:102:8
```

The failed tests were:

```sh
waiting...
S: Spacebars.call
waiting...
S: Spacebars.dot
waiting...
C: Spacebars.call
waiting...
C: Spacebars.dot
```

**Review by StorytellerCZ — APPROVED** [review]
We should probably update other dependencies as well.

**Comment by Grubba27** [comment]
How are you running locally? it has differences if you are using the meteor from the checkout or your global meteor (I discovered this in the worst way 😢 )

> We should probably update other dependencies as well.

I'm afraid that this will take some time. But if everyone is onboard we can do it.
I asked @jankapunkt because I want to release blaze 2.7 as soon as possible so we can have a working version of blaze with meteor 3.0 and the async api

**Review by Grubba27 — APPROVED** [review]
CI is green = LGMT!

**Pull request merged**
