### PR TITLE
Release 2.4

### PR DESCRIPTION
**Pull request by filipenevola**
As we have many big PRs right now in progress we are grouping them in this branch.

This branch was started from `hot-module-replacement` branch.

## Beta
beta.3 is out. Our goal is to have beta.3 as our latest beta.

### How to test 2.4

```shell
meteor add blaze-html-templates@1.2.0-beta.3
```

### How to test 2.4 with HMR

You can try this integration in apps using Meteor 2 or newer by running:

```shell
meteor add hot-module-replacement blaze-html-templates@1.2.0-beta.3
```

To also use HMR for javascript files that use the Template api, run

```shell
meteor add blaze-hot
```

### CODE REVIEW

**Comment by filipenevola** [comment]
The two test failures are coming from the HMR branch, @zodern is going to fix them soon.

**Comment by brucejo75** [comment]
submitted #325

**Comment by nathan-muir** [comment]
#319 Fixed a few situations where the template compiler wouldn't optimise it's output javascript.

Should make rendering faster (if the initial optimisation reasoning holds true)

#321 Just source code modernisation, making it easier to read. Shouldn't change any API's; except may need explicit import if other packages are using directly.

#324 Add a `whitespace="strip"` option to templates, which removes any whitespace that crosses newlines.

**Comment by jankapunkt** [comment]
I added the hmr and the beta, actually get the following message  in a constant interval:

```
Firefox can’t establish a connection to the server at ws://localhost:3000/__meteor__hmr__/websocket. hot-module-replacement.js:290:11
error
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: WebSocket { url: "ws://localhost:3000/__meteor__hmr__/websocket", readyState: 3, bufferedAmount: 0, … }
​
isTrusted: true
​
originalTarget: WebSocket { url: "ws://localhost:3000/__meteor__hmr__/websocket", readyState: 3, bufferedAmount: 0, … }
​
returnValue: true
​
srcElement: WebSocket { url: "ws://localhost:3000/__meteor__hmr__/websocket", readyState: 3, bufferedAmount: 0, … }
​
target: WebSocket { url: "ws://localhost:3000/__meteor__hmr__/websocket", readyState: 3, bufferedAmount: 0, … }
​
timeStamp: 154742
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }

HMR: websocket closed hot-module-replacement.js:294:13
```

**Comment by filipenevola** [comment]
@jankapunkt are you running Meteor 2 or newer?

cc @zodern

**Comment by zodern** [comment]
@jankapunkt you need to restart Meteor after adding the `hot-module-replacement` package so Meteor starts with HMR Server.

**Comment by jankapunkt** [comment]
@zodern thx that works, didn't read carefully enough and just added the packages via editing .meteor/packages besides that there are no issues found yet. However, I have another app where I intercept/override lots of Template.prototype functions so I will check this out as well.

**Comment by jankapunkt** [comment]
@filipenevola is there something left that needs to be done to move forward 2.4? Anywhere where we can help? The HMR is working really smooth so far, still no errors, even with my packages that hook deeply into the Templates.

**Comment by filipenevola** [comment]
> @filipenevola is there something left that needs to be done to move forward 2.4? Anywhere where we can help? The HMR is working really smooth so far, still no errors, even with my packages that hook deeply into the Templates.

There is nothing left. We are going to release in the next days. 💪

**Comment by filipenevola** [comment]
Blaze 2.4 is out!

New versions:

```bash
Published htmljs@1.1.0.                       
Publishing html-tools                         
Published html-tools@1.1.0.                                                        
Publishing blaze-tools                        
Published blaze-tools@1.1.0.                                                       
Publishing spacebars-compiler                 
spacebars-compiler: updating npm dependencies -- uglify-js...                      
Published spacebars-compiler@1.2.0.           
Publishing templating-tools                   
Published templating-tools@1.2.0.                                                  
Publishing caching-html-compiler              
Published caching-html-compiler@1.2.0.                                             
Publishing static-html                        
Published static-html@1.3.0.                                                       
Publishing blaze                              
Published blaze@2.4.0.                        
Publishing spacebars                          
Published spacebars@1.1.0.                                                         
Publishing templating-compiler                
Published templating-compiler@1.4.0.          
Publishing templating-runtime                 
Published templating-runtime@1.4.0.                                                
Publishing blaze-hot                          
Published blaze-hot@1.0.0.                                                         
Publishing templating                         
Published templating@1.4.0.                   
Publishing spacebars-tests                    
Published spacebars-tests@1.2.0.                                                   
Publishing blaze-html-templates               
Published blaze-html-templates@1.2.0.         
```

**Pull request merged**
